### ISSUE TITLE
Log full request

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/formsender#51]
We should log the full request from the user for two reasons:
1. The request fails, we should have a record of what was requested so we can act on it.
2. The request succeeds, but we want a record of what was originally requested by the user in the future.

**Comment by ramereth** [comment]
Some addition information would be nice:

* [ ] Add some useful debug output when working on the app
* [ ] The default logging output could use some more information: Name, Project, send_to from_email

**Comment by Kennric** [comment]
Fixed and merged.
