### ISSUE TITLE
Optionally append project name to email subject

### ISSUE THREAD

**Issue by ramereth** [osuosl/formsender#56]
For anything going into RT, we generally prefer having the name of the project included in the email subject. Perhaps the subject heading we're doing in the html side of things can just be a prefix and optionally send a field name to be used in the email subject.

**Comment by matthewrsj** [comment]
@ramereth this functionality exists how I believe you are describing it here. We can customize the message by explicitly setting it in the form with a hidden field called `message_subject`.

This **does not** let you dynamically set the subject to the specified project name. I will modify the `message_subject` field to take a field name, such as `project` and set the subject to be the user input for that field.

**Comment by matthewrsj** [comment]
Fixed by #59
